Depression Screening and Follow-Up for Adolescents and Adults (CQL)
amida-tech/cql-execution pull request #11
Opened 2021-03-05 21:06 UTC by hmayenve

# Related Tickets

- [SAR-75](https://jira.amida-tech.com/browse/SAR-94)

# Other Repos' PR(s) Intended to Work With This PR

# How Things Worked (or Didn't) Before This PR
There was no CQL and associated files for Depression Screening and Follow-Up for Adolescents and Adults

# How Things Work Now (And How to Test)
## How it works now
I've added the CQL and associated files for Depression Screening and Follow-Up for Adolescents and Adults

## To test
run `yarn` to install the necessary packages
run `node exec-files/exec-depression-screening.js `
Use your favorite diffchecker to confirm your output for patientResults and unfilteredResults matches what is below - you can ignore everything else.
```javascript
{ 'numer-EXAMPLE1-FHIR4':
   { 'First Predecessor Year':
      Interval { low: [Date], high: [Date], lowClosed: true, highClosed: false },
     'Lookback Interval One More Year':
      Interval { low: [Date], high: [Date], lowClosed: true, highClosed: false },
     Patient:
      FHIRObject {
        identifier: [Getter],
        active: [Getter],
        name: [Getter],
        telecom: [Getter],
        gender: [Getter],
        birthDate: [Getter],
        deceased: [Getter],
        address: [Getter],
        maritalStatus: [Getter],
        multipleBirth: [Getter],
        photo: [Getter],
        contact: [Getter],
        communication: [Getter],
        generalPractitioner: [Getter],
        managingOrganization: [Getter],
        link: [Getter],
        text: [Getter],
        contained: [Getter],
        extension: [Getter],
        modifierExtension: [Getter],
        id: [Getter],
        meta: [Getter],
        implicitRules: [Getter],
        language: [Getter] },
     'Initial Population': true,
     'Bipolar Disorder Reports': [ [FHIRObject], [FHIRObject] ],
     'Denominator Exclusion': true,
     'Denominator 1': 1,
     'Numerator 1': 1,
     'Positive Depression Screening During Follow-Up Period': [ [FHIRObject] ],
     'Denominator 2': 1,
     'First Positive Depression Screening During Follow-Up Period': [ [FHIRObject] ],
     'Dispensed Antidepressant Within 31 Days': [ [FHIRObject] ],
     'Follow-Up Care Encounters': [ [FHIRObject], [FHIRObject], [FHIRObject] ],
     'Follow-Up Encounter Within 31 Days': [],
     'Same Day Behavioral Encounter': [ [FHIRObject] ],
     'Negative Depression Screening Within 31 Days': [ [FHIRObject] ],
     'Numerator 2': 1,
     'Stratifier 1': false,
     'Stratifier 2': true,
     'Stratifier 3': false,
     'Stratifier 4': false },
  'numer-EXAMPLE2-FHIR4':
   { 'First Predecessor Year':
      Interval { low: [Date], high: [Date], lowClosed: true, highClosed: false },
     'Lookback Interval One More Year':
      Interval { low: [Date], high: [Date], lowClosed: true, highClosed: false },
     Patient:
      FHIRObject {
        identifier: [Getter],
        active: [Getter],
        name: [Getter],
        telecom: [Getter],
        gender: [Getter],
        birthDate: [Getter],
        deceased: [Getter],
        address: [Getter],
        maritalStatus: [Getter],
        multipleBirth: [Getter],
        photo: [Getter],
        contact: [Getter],
        communication: [Getter],
        generalPractitioner: [Getter],
        managingOrganization: [Getter],
        link: [Getter],
        text: [Getter],
        contained: [Getter],
        extension: [Getter],
        modifierExtension: [Getter],
        id: [Getter],
        meta: [Getter],
        implicitRules: [Getter],
        language: [Getter] },
     'Initial Population': false,
     'Bipolar Disorder Reports': [ [FHIRObject], [FHIRObject] ],
     'Denominator Exclusion': true,
     'Denominator 1': 0,
     'Numerator 1': 0,
     'Positive Depression Screening During Follow-Up Period': [ [FHIRObject] ],
     'Denominator 2': 0,
     'First Positive Depression Screening During Follow-Up Period': [ [FHIRObject] ],
     'Dispensed Antidepressant Within 31 Days': [ [FHIRObject] ],
     'Follow-Up Care Encounters': [ [FHIRObject], [FHIRObject], [FHIRObject] ],
     'Follow-Up Encounter Within 31 Days': [],
     'Same Day Behavioral Encounter': [ [FHIRObject] ],
     'Negative Depression Screening Within 31 Days': [ [FHIRObject] ],
     'Numerator 2': 0,
     'Stratifier 1': false,
     'Stratifier 2': false,
     'Stratifier 3': false,
     'Stratifier 4': false } }
{ 'Denominator Count': 2,
  'Numerator Count': 2,
  'CDC Measure Score': 1 }
```
## To Review
Here's what to look for in each different file:

`exec-depression-screening.js` - This is the exec file that actually does the work - there's not much to review here.

`depression-screening-follow-up-codes.js` - The list of codes in each value set. This is programmatically generated using the CQL from the [VSAC](https://vsac.nlm.nih.gov/) API, so there's nothing to review here

`depression-screening.json` - JSON version of the CQL created using the [clinical_quality_language](https://github.com/cqframework/clinical_quality_language) - nothing to review here

`depression-screening-follow-up.json` - This contains the fake patients and their data. If you are really gung-ho, you can review the output of the results and confirm that the expressions with the CQL library returned the correct response based on the data, but that might take a while.

`depression-screening.cql` - this is the main piece of the PR. Read through the following requirements, and as best you can, confirm that the CQL matches the guidelines. If you'd prefer, whenever you get to this portion I can send you the word doc these requirements are in, which might be easier than looking at screenshots.

### Use `K. Health Plan Description AND ECDS_pp 557-650.docx` in the HEDIS textbook `pages 602-606`

2021-03-08 18:13 UTC, TylerNoblett requested changes
Good work! This HEDIS measure is a little different in that it doesn't tell you in each step what valuesets to use (and instead just gives all the valuesets at the bottom) so I had a harder time comparing the measure to the code which resulted in a lot of questions 😅

2021-03-08 18:13 UTC, TylerNoblett commented on cql/depression-screening.cql
> +	return NegativeScreen
same as above - what portion of the measure does this map to? It seems like it fits into this category (maybe?) but this category deals with same day
> Receipt of an assessment on the same day and subsequent to the positive screen.
–	Documentation of additional depression screening indicating either no depression or no symptoms that require follow-up. For example, if the initial positive screen resulted from a PHQ-2 score, documentation of a negative finding from a subsequent PHQ-9 qualifies as evidence of 
follow-up.

2021-03-08 18:13 UTC, TylerNoblett commented on cql/depression-screening.cql
> +	return NegativeScreen
also, I don't see `Negative Depression Screening` in the list of valuesets (though the spec above doesn't really make it clear how you're supposed to calculate this value) - how did you know to use this (maybe it was in the code you found online I'm guessing)?

2021-03-08 18:13 UTC, TylerNoblett commented on cql/depression-screening.cql
> +	return Antidepressants
👍 I get this one!

2021-03-08 18:13 UTC, TylerNoblett commented on cql/depression-screening.cql
> +				with [DiagnosticReport: "Dysthymia"] D
the spec references these two follow-up encounters `outpatient or telephone follow-up visit`, but  I don't see either of them here and I'm not sure where `Ambulatory/ED Visit` and `Dysthymia` come from - can you help me understand?

2021-03-10 02:27 UTC, hmayenve commented on cql/depression-screening.cql
> +//using FHIR version '3.0.1'
correct, will remove this. good catch!

2021-03-10 02:28 UTC, hmayenve commented on cql/depression-screening.cql
> +//valueset "Bipolar Disorder": '2.16.840.1.113883.3.464.1004.1044'
Yeah I thought it would be a good idea for when we get real data and figure out how to extract the value sets in the spreadsheet

2021-03-10 02:29 UTC, hmayenve commented on cql/depression-screening.cql
> +parameter "Measurement Period" default Interval[@2019-01-01, @2020-01-01]
ok yeah i can update it to 2020, ill probably need to update the patient data as well. I also agree that I dont think we need to include the time portions

2021-03-10 02:35 UTC, hmayenve commented on cql/depression-screening.cql
> +define function PeriodToIntervalOfDT(value FHIR.Period):
ty! 😊

2021-03-11 12:50 UTC, hmayenve commented on cql/depression-screening.cql
> +			where BD.status.value in { 'preliminary', 'final', 'amended', 'corrected', 'appended' }
In my opinion, we need to check the status because there are status that indicate either an error, unknown, or that the is no data to report. I think we should only care about the reports with status `'preliminary', 'final', 'amended', 'corrected', 'appended'` since those indicate that some sort of data is in them. Refer to https://hl7.org/fhir/R4/valueset-diagnostic-report-status.html so see the descriptions of each of the status. This is of couse my interpretation, and I am not fully sure either.

2021-03-11 12:58 UTC, hmayenve commented on cql/depression-screening.cql
> +				and PeriodToIntervalOfDT(BD.effective) overlaps "Lookback Interval One More Year"
you're correct, good catch

2021-03-11 13:11 UTC, hmayenve commented on cql/depression-screening.cql
> +				and PeriodToIntervalOfDT(MDD.effective) overlaps "First Predecessor Year"
dysthymia is defined as having depression for at least two years. This means that if a diagnostic report has dysthymia in it that means that the patient had depression the year prior to the Measurement Period. Im not sure if there is a better to this this though. Im open to changing it to something that we can all agree lol

2021-03-11 13:17 UTC, hmayenve commented on cql/depression-screening.cql
> +	AgeInYearsAt(start of "Measurement Period") >= 65
No, I don't. I just included it because the code that I found online had it. I dont see how these go into the final measure score though. I ask Mike and he didnt know either.

2021-03-11 13:36 UTC, hmayenve commented on cql/depression-screening.cql
> +		[Encounter: "Behavioral Health Follow-up Visit"]
sure, i can do that.

2021-03-11 13:55 UTC, hmayenve commented on cql/depression-screening.cql
> +  Sum("Numerator Count") / Sum("Denominator Count")
yeah, Mike said to just treat as 2 separate score so im going to do that.

2021-03-15 14:41 UTC, TylerNoblett commented on cql/depression-screening.cql
> +			where BD.status.value in { 'preliminary', 'final', 'amended', 'corrected', 'appended' }
ahh this is really good! I agree with your approach

2021-03-16 20:32 UTC, JamesbZhu requested changes

2021-03-16 20:32 UTC, JamesbZhu commented on cql/depression-screening.cql
> +			[Encounter: "Follow Up Visit"] E
does this section map to the  "An outpatient or telephone follow-up visit with a diagnosis of depression or other behavioral health condition" bullet in the HEDIS spec?  if so, how are we specifying the "outpatient" or "telephone" encounters and the "other behavioral health condition"?

2021-03-16 20:32 UTC, JamesbZhu commented on cql/depression-screening.cql
> +	return NegativeScreen
on the same page with @TylerNoblett here, seems like we should be combining "Negative Depression Screening Within 31 Days" and "Same Day Behavioral Encounter" somehow

2021-03-16 20:32 UTC, JamesbZhu commented on cql/depression-screening.cql
> +	return BehavioralEncounter
the spec for this part is a bit confusing for me. It says in the 'same day' portion that `Receipt of an **assessment** on the same day and subsequent to the positive screen` but also `Documentation of an additional **depression screening** indicating either no depression or no symptoms that require follow-up`.  Not sure if  "assessment"  == "depression screening" in this case, or if assessment encapsulates more than just a depression screening observation.  Either way, would it make sense to include a negative depression screening here after the first positive screen?

2021-03-16 20:32 UTC, JamesbZhu commented on cql/depression-screening.cql
> +define "CDC Measure Score 1":
i think this should be DSF instead of CDC

2021-03-16 20:32 UTC, JamesbZhu commented on cql/depression-screening.cql
> +define function PeriodToIntervalOfDT(value FHIR.Period):
agreed! this is super neat 🔥

2021-03-18 19:43 UTC, hmayenve commented on cql/depression-screening.cql
> +define "CDC Measure Score 1":
yep, good catch!

2021-03-18 20:40 UTC, hmayenve commented on cql/depression-screening.cql
> +			[Encounter: "Follow Up Visit"] E
Got it, im going to check the Encounter.class to check whether is outpatient or telephone.

2021-03-22 11:28 UTC, hmayenve commented on cql/depression-screening.cql
> +	))
got it

2021-03-22 11:45 UTC, hmayenve commented on cql/depression-screening.cql
> +	case("Initial Population"
got it

2021-03-22 12:55 UTC, hmayenve commented on cql/depression-screening.cql
> +	return NegativeScreen
Yes @TylerNoblett this portion maps to the spec you specified. I have created a function that puts the same day and the negative depression screening together. Also, the `Negative Depression Screening` valueset came from th VSAC. On Friday, we all agree to use valuesets in VSAC that are not in the spec. We would need a SME to be able to know what the equivalent of the `Negative Depression Screening` value set is in the HEDIS spec in order to not use the VSAC one.

2021-03-22 12:55 UTC, hmayenve commented on cql/depression-screening.cql
> +	return NegativeScreen
yes @JamesbZhu I have combined the "Negative Depression Screening Within 31 Days" and "Same Day Behavioral Encounter"

2021-03-22 12:59 UTC, hmayenve commented on cql/depression-screening.cql
> +	return BehavioralEncounter
yes, I have created another expression that includes/joins the two.

2021-03-22 13:14 UTC, hmayenve commented on cql/depression-screening.cql
> +	[Observation: "Positive Depression Screening"] PositiveScreen
got it, i'll union `Depression Screen` and `Positive Depression Screening`

2021-03-22 14:30 UTC, TylerNoblett commented on cql/depression-screening.cql
> +	return NegativeScreen
yeah that new denom 2 check makes sense to me (as far as it would given the valuesets we're working with)

2021-03-22 14:30 UTC, TylerNoblett approved these changes
LGTM!

2021-03-25 19:29 UTC, JamesbZhu approved these changes
LGTM!

2021-03-25 19:51 UTC, merged