Feature/sar 75 diabetes—bp control hedis measure
amida-tech/cql-execution pull request #8
Opened 2021-01-06 18:56 UTC by TylerNoblett

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository.
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [ ] This pull request describes why these changes were made
- [ ] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass
- [ ] Code coverage has not gone down and all code touched or added is covered.
- [ ] Code passes lint and prettier (hint: use `yarn run test:plus` to run tests, lint, and prettier)
- [ ] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [ ] `cql4browsers.js` built with `yarn run build:browserify` if source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2021-01-21 15:49 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +library cdc_bp_lessThanOneHundredAndFortyOverNinety version '1'
This file is very similar to the HbA1c file - in the future, it would make the most sense to make a base diabetes library that is imported into the HbA1c and BP CQL files, but we'll worry about that later

2021-01-21 15:50 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +library cdc_bp_lessThanOneHundredAndFortyOverNinety version '1'
Just in case you missed it in the "Conversation" section, you only need to review a few expressions in the CQL file - you can determine the specific ones by doing a diff check between this CQL and the HbA1c CQL

2021-01-29 18:01 UTC, JamesbZhu requested changes
couple of small things to consider - i wrote some comments. but other than that it looks good to me!

2021-01-29 18:17 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +    and "Diabetes Diagnosis By Medication"
whoops! Those are not supposed to be the same

2021-01-29 18:18 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +library cdc_bp_lessThanOneHundredAndFortyOverNinety version '1'
yeah - I need to update this file with the additions you made to HbA1c since they're supposed to almost be the same

2021-01-29 18:18 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +            and DiastolicBP.value.unit in {'mm[Hg]', 'mmHg'}
ahhh that's a good point! I'll see if there are otehr common units I can include

2021-01-29 18:19 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +	["Observation": "Blood pressure"] BloodPressure
good question 🤔

2021-01-29 18:19 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +	["Observation": "Blood pressure"] BloodPressure
I'll look into that

2021-02-01 19:45 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +            and DiastolicBP.value.unit in {'mm[Hg]', 'mmHg'}
I asked Emily and she said that's the universal unit of measurement for BP levels, but it probably wouldn't hurt to also ask a SME

2021-02-01 20:01 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +    and "Diabetes Diagnosis By Medication"
ah - there is actually a difference - one has 'or' while the other has 'and'

2021-02-01 20:37 UTC, TylerNoblett commented on cql/cdc_diabetes-bp.cql
> +	["Observation": "Blood pressure"] BloodPressure
changed it!

2021-02-03 17:51 UTC, JamesbZhu commented on cql/cdc_diabetes-bp.cql
> +            and DiastolicBP.value.unit in {'mm[Hg]', 'mmHg'}
got it, nice!

2021-02-22 19:26 UTC, hmayenve approved these changes
LGTM. Great job! 🎉 👍  Basically is the same as a1c but instead of the requirements for A1C control < 8, we are doing BP control < 140/90 mm Hg.

2021-02-24 22:48 UTC, JamesbZhu approved these changes
LGTM

2021-02-25 12:18 UTC, merged